### ISSUE TITLE
Build issue: "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)"

### ISSUE THREAD

**Issue by DeeDeeG** [13rac1/scfbuild#14]
```
DEBUG:scfbuild.builder:Found Ligature Glyph: 1f4aa-1f3fe
DEBUG:scfbuild.util:Found SVG width/height (128.00/128.00)
DEBUG:scfbuild.builder:Set SVG transform: translate(0 -6.75) translate(0,-1638.4) scale(16.0)
DEBUG:scfbuild.builder:Glyph ID: 878 Adding SVG: build/svg-color/1f4aa-1f3fe.svg
DEBUG:scfbuild.builder:Found regular Glyph: u1F64E
DEBUG:scfbuild.util:Found SVG width/height (128.00/128.00)
DEBUG:scfbuild.builder:Set SVG transform: translate(0 -6.75) translate(0,-1638.4) scale(16.0)
DEBUG:scfbuild.builder:Glyph ID: 616 Adding SVG: build/svg-color/1f64e.svg
DEBUG:scfbuild.builder:Found Ligature Glyph: 1f47c-1f3ff
DEBUG:scfbuild.util:Found SVG width/height (128.00/128.00)
DEBUG:scfbuild.builder:Set SVG transform: translate(0 -6.75) translate(0,-1638.4) scale(16.0)
Traceback (most recent call last):
  File "SCFBuild/bin/scfbuild", line 17, in <module> 
    sys.exit(main())
  File "/home/mint/noto-color-emoji-font/SCFBuild/scfbuild/main.py", line 124, in main
    return builder.run()
  File "/home/mint/noto-color-emoji-font/SCFBuild/scfbuild/builder.py", line 74, in run
    self.add_color_svg()
  File "/home/mint/noto-color-emoji-font/SCFBuild/scfbuild/builder.py", line 139, in add_color_svg
    data = ET.tostring(svg_root, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1127, in tostring
    return "".join(data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)
Makefile:94: recipe for target 'build/NotoColorEmoji-SVGinOT-OSX.ttf' failed
make: *** [build/NotoColorEmoji-SVGinOT-OSX.ttf] Error 1
```

I've been working on this for a bit, and I've been running into this issue. When I try to build Noto Color Emoji, with SVGs from Google's 'Noto Emoji' repo, I get errors and it (SCFBuild) doesn't output the font files. I'd be happy to give more details if they're needed.

**Comment by DeeDeeG** [comment]
I narrowed it down to some glitchy SVGs. They happen to be the "baby angel" emoji.

I'm not sure what about them causes the issue. The color output svgs look a little weird in my file browser:

![color output](https://user-images.githubusercontent.com/20157115/28242839-b13d470c-6984-11e7-8335-780567165fbe.png)

Here is what the black and white output looks like:

![bw output](https://user-images.githubusercontent.com/20157115/28242853-0663fd34-6985-11e7-8ab1-15c2f62fba7f.png)

These output svgs look fine in Inkscape. I have attached the originals from the Noto Emoji repo, and the optimized (color/bw) outputs SCFBuild generates on my system.

[glitchy svgs.zip](https://github.com/eosrei/scfbuild/files/1150632/glitchy.svgs.zip)

**Comment by DeeDeeG** [comment]
I figured out how to modify these svgs to workaround the problem.

There is nothing "wrong" with the svgs themselves, so I consider this a bug with SCFBuild, unfortunately.

What happened was, these SVGs included a tag as follows: `<g id="图层_1">`

Which is Chinese meaning "Layer_1". It is a tag that Adobe Illustrator sometimes adds. It apparently adds the tag in the same language that the program's GUI uses, or something like that.

Part of SCFBuild relies on code from python that expects ASCII-only values. The Chinese characters in that tag are out-of-range for ASCII, and the python code errors out.

I manually changed the tags to read `<g id="Layer_1">` and the build completes without errors.

**Comment by 13rac1** [comment]
Ah ha! I'll see what can be done to make the ElementTree library happy.

Thanks for thoroughly debugging this!

**Comment by DeeDeeG** [comment]
No problem!

By the way, building a font with just the baby angel emojis I attached above makes for a fairly compact test-case... In case that would be handy.

**Comment by 13rac1** [comment]
This is going to be such a hassle in Python2. I've been hoping for FontForge to support Python3, which I would have used in the first place if I could.

**Comment by 13rac1** [comment]
Might be fixed now with Python3 support? https://github.com/13rac1/scfbuild/commit/6d84339512a892972185d894704efa67dd82e87a

**Comment by DeeDeeG** [comment]
Hi again! It's been a bit!

I took a look at this. Can confirm, this error doesn't occur on Python 3.

The error still occurs if attempting to use Python 2, but it seems like Python 2 isn't meant to be 100% supported anymore, especially given that the shebang for `bin/scfbuild` now hard-codes `python3`.

---

To test, I was on Ubuntu 20.04. I cloned twemoji-color-font and followed the build instructions, installing any needed dependencies. Then I replaced `assets/twemoji-svg/*.svg` with the source svgs linked above (from `glitchy.svgs.zip`). Works just fine with Python 3.

To test with Python 2, I had to grab a bunch of old Python 2-related packages (`python-fontforge`, `python-yaml`, several  indirect dependencies to support those) from here: https://packages.ubuntu.com/ For example: https://packages.ubuntu.com/bionic/python-fontforge --> https://packages.ubuntu.com/bionic/amd64/python-fontforge/download --> http://mirrors.kernel.org/ubuntu/pool/universe/f/fontforge/python-fontforge_20170731~dfsg-1_amd64.deb Also had to edit the shebang line of `SCFBuild/bin/scfbuild` to point at `python2`. Can confirm this is still broken on Python 2, but it seems that much is expected.

**Comment by 13rac1** [comment]
> It's been a bit!

:flushed: I've been working on many other projects.

It's probably best to just call this "fixed" then. Python2 is EOL. The codebase generally works with Python2, but I'm not concerned with supporting it. Thank you for testing it out thoroughly with steps to reproduce.
