### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by b-g** [13rac1/scfbuild#15]
Hi there! Currently looking into ways to create a colorfont for our http://openmoji.org/ project. Very happy that I found scfbuild! Our [svg file structure](https://github.com/hfg-gmuend/openmoji/tree/master/color/svg) seems also work nicely out of the box with it ... Just I'm having trouble to get it to run :)

```
$ bin/scfbuild
Traceback (most recent call last):
  File "bin/scfbuild", line 14, in <module>
    from scfbuild.main import main
  File "/Users/bene/Documents/scfbuild/scfbuild/main.py", line 15, in <module>
    import yaml
ImportError: No module named yaml
```

As `pip search yaml` yields a lot of yaml python modules ... I wondering which one to pick. Any setup hints are very welcome. Thanks.

**Comment by 13rac1** [comment]
Ah! I didn't realize this dependency was required. I use
`sudo apt install python-yaml`

Looks like you are on a Mac.

https://packages.ubuntu.com/trusty/python-yaml Says this is `pyyaml`.

**Comment by b-g** [comment]
@eosrei Many thanks! Works! :)

This is document how to install **scfbuild** on macOS (tested with 10.12.6, Python 2.7.10, Homebrew 1.7.1). 

```
pip install fonttools
pip install pyyaml
brew install fontforge --with-python
```

It might be nice to add those hints to the readme (happy to do a PR if you want).
