### ISSUE TITLE
Windows10: New SVGinOT processor doesn't handle SVG viewbox

### ISSUE THREAD

**Issue by 13rac1** [13rac1/scfbuild#7]
Details in https://github.com/eosrei/emojione-color-font/issues/50

Solution is probably to transform all SVGs to 2048x2048 glyph scale and use `transform="scale(1,-1)"` as described in #4

**Comment by RoelN** [comment]
I'm not sure if you already considered this, but I've been experimenting with manually inserted SVGs and using this transform on the encapsulating `<g>`:

`<g transform="scale(10.24) translate(0, -2048)>`

The unitsPerEm value is 2048, the height of the original SVG is 200px. This determines the scale value: `unitsPerEm / height of SVG`, in this case 10.24. The translate can then always be `-unitsPerEm` for the Y axis.

I strip the `viewBox` attribute so it becomes the same as the SVG's width and height — this could cause problems for SVGs that have a deliberate `viewBox` that actually determines the proper look.

This way the original SVG doesn't needs to be rewritten. Maybe this is of use?

_EDIT:_ This assumes the SVG is already the correct way up, e.g. using the SVG y-axis.

**Comment by 13rac1** [comment]
The original SVG doesn't need to be rewritten, but it can/should be for efficiency.

That's similar to the transform I found to fix the EmojiOne graphics: 

```
<g transform="translate(0,-2048) scale(32)">
```

I've been super busy with work the last two weeks. ASAP I am going to rewrite the  to calculate the ideal transform. Optimizing via SVGO will come later.

Note: I use the `viewBox` to calculate glyph width for the b&w glyphs: https://github.com/eosrei/scfbuild/blob/master/scfbuild/util.py#L72 height/width/viewbox isn't needed in the end result, but is needed in the source.

**Comment by 13rac1** [comment]
Oh no! My lack of time to implement is making w3c think it's a bug in Edge! Gah! Haha!

https://www.w3.org/community/svgopentype/2016/08/15/chromatic-fonts-implementation-roundup/
